# Generated by Django 5.0.3 on 2024-03-10 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('leagueid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('leaguename', models.CharField(max_length=500)),
                ('altleaguename', models.CharField(max_length=500)),
                ('leaguedescription', models.TextField(max_length=4000)),
                ('leaguecountry', models.CharField(max_length=500)),
                ('seasonformat', models.CharField(max_length=500)),
                ('leaguesport', models.CharField(max_length=500)),
                ('leaguebadge', models.CharField(max_length=500)),
                ('teamdata', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('teamname', models.CharField(max_length=500)),
                ('altteamname', models.CharField(max_length=500)),
                ('teamdescription', models.TextField(max_length=4000)),
                ('teamcountry', models.CharField(max_length=500)),
                ('teamstadium', models.CharField(max_length=500)),
                ('teamgender', models.CharField(max_length=500)),
                ('teamsport', models.CharField(max_length=500)),
                ('teambadge', models.CharField(max_length=500, null=True)),
                ('leagues', models.ManyToManyField(related_name='teams', to='sportsdb.league')),
                ('primaryleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_teams', to='sportsdb.league')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('matchteams', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=255)),
                ('matchday', models.IntegerField()),
                ('hometeam', models.CharField(max_length=255)),
                ('awayteam', models.CharField(max_length=255)),
                ('homescore', models.IntegerField(null=True)),
                ('awayscore', models.IntegerField(null=True)),
                ('season', models.CharField(max_length=255)),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(max_length=255, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('badge', models.CharField(max_length=255, null=True)),
                ('video', models.CharField(max_length=255, null=True)),
                ('leagueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsdb.league')),
                ('awayteamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='sportsdb.team')),
                ('hometeamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='sportsdb.team')),
            ],
        ),
    ]
