# Generated by Django 5.0.3 on 2024-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='altleaguename',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='leaguebadge',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='leaguedescription',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='altteamname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamdescription',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
