# Generated by Django 5.0.3 on 2024-03-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsdb', '0002_alter_league_altleaguename_alter_league_leaguebadge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
