# Generated by Django 5.0.3 on 2024-03-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsdb', '0003_alter_match_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('standingid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('rank', models.IntegerField()),
                ('form', models.CharField(max_length=255)),
                ('played', models.IntegerField()),
                ('season', models.CharField(max_length=255)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('goalsfor', models.IntegerField()),
                ('goalsagainst', models.IntegerField()),
                ('goaldiff', models.IntegerField()),
                ('points', models.IntegerField()),
                ('standingtime', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='sportsdb.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='sportsdb.team')),
            ],
        ),
    ]
