# Generated by Django 5.0.3 on 2024-03-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportsdb', '0003_alter_match_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('useremail', models.CharField(max_length=255)),
                ('userteams', models.ManyToManyField(related_name='teams', to='sportsdb.team')),
            ],
        ),
    ]
