# Generated by Django 5.0.3 on 2024-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsdb', '0004_standing'),
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='sportsdb.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userteams',
            field=models.ManyToManyField(related_name='teamss', to='sportsdb.team'),
        ),
    ]
