# Generated by Django 5.0.3 on 2024-03-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='ass@email.com', max_length=255, unique=True),
        ),
    ]
